### ISSUE TITLE
issue vod playing

### ISSUE THREAD

**Issue by Bluejasmine02** [esseivan/TwitchRecoverCSharp#2]
hello,
trying to recover a vod. it was deleted yesterday. I used the link, I got one (the mu83). I tried putting it in vlc, but it didn't work. it gave me the time stamp of the entire stream, then went back to 0. 
how do I fix this.

thank you, 
bluejasmine

**Comment by esseivan** [comment]
I didn't fixed for deleted VODs. Maybe the original repository is working for them but as I saw, it requires more stuff to be done
